label: 'GA4GH::SchemaBlocks'
tagline: 'An Initiative by Members of the Global Alliance for Genomics and Health'
description: |
  SchemaBlocks is a cross-workstream project of the Global Alliance for Genomics & Health
keywords: genomics, cloud, Beacon, DNA, sharing, GA4GH
site_domain_name: schemablocks.org
url: 'https://schemablocks.org'
baseurl: ""
site_parent_link: 'https://ga4gh.org'
github_organisation: ga4gh-schemablocks
show_downloads: true
future: true

# instructions for processing specific directories

include:
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag
collections_dir: pages
collections:
  news:
    output: true
    permalink: /news/:path/
  schemas:
    output: true
    permalink: /schemas/:path/
  formats:
    output: true
    permalink: /formats/:path/
  people:
    output: true
    permalink: /people/:path/
  howto:
    output: true
    permalink: /howto/:path/
  minutes:
    output: true
    permalink: /minutes/:path/
    
# navigation blocks can be used to separate different categories and add e.g. 
# external link block(s), in combination with a properly modified layout

nav_cat_blocks:
  General: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'

General:
  news: News
  people: Participants
  formats: 'Data Formats'
  schemas: 'Data Schemas'
  howto: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

related_sites: 
  'GA4GH::Discovery': 'http://ga4gh-discovery.github.io'
  'GA4GH::CLP': 'http://ga4gh-cp.github.io'
  'GA4GH::GKS': 'http://ga4gh-gks.github.io'
  'SchemaBlocks at Metadata': 'http://ga4gh-metadata.github.io/SchemaBlocks/'
  'ELIXIR beacon': 'http://ga4gh-beacon.github.io'
  Phenopackets: 'http://github.com/phenopackets'
  GA4GH: 'http://www.ga4gh.org'
  'Beacon<span style="color: red; font-weight: 800;">+</span>': 'http://beacon.progenetix.org'
  
# tag_cloud items

cloud_tags:
  - Beacon
  - CP
  - Discovery
  - GA4GH
  - GKS
  - MME
  - admins
  - contacts
  - contributors
  - coordinates
  - dates
  - developers
  - identifiers
  - leads
  - press
  - times

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
navigation_max_items: 4 # number of shown links in current category
emptyArray: []          # dummy element for array initialisation
